version: "3"

services:

  motioneye:
    build: .
    container_name: motion
    restart: always
    environment:
      - VIRTUAL_HOST=motion.gareth.id.au
    networks:
      - outside
    expose:
      - "8765"
    volumes:
      - motioneye-config:/etc/motioneye
      - motioneye-data:/var/lib/motioneye

volumes:
  motioneye-config:
    driver: convoy
  motioneye-data:
    driver: convoy

network:
  outside:
    external: true
